"""Build Round 2/3 structured contracts from current-agent decisions and blackboard history."""
import argparse,json
from pathlib import Path
import jsonschema
ROOT=Path(__file__).resolve().parents[2];EXP=ROOT/'try4';ap=argparse.ArgumentParser();ap.add_argument('--round',type=int,required=True);a=ap.parse_args();r=a.round;dec=json.loads((EXP/f'codex_authored/T2/round{r}_decisions.json').read_text());schema=json.loads((EXP/'schemas/repair_contract.schema.json').read_text())
for d in dec['decisions']:
 pid=d['part_id'];ps=json.loads((EXP/'T2'/pid/f'round_{r-1}/part_state.json').read_text());assert ps['state'] in ('LOCAL_REPAIR','REPLAN');prev=ps['previous_metrics'] if '#' in ps['accepted_metrics'] else json.loads((EXP/ps['accepted_metrics']).read_text());source=(EXP/ps['current_artifact']).parent;fg=json.loads((source/'feature_graph.json').read_text())['features'];feature=fg[0]
 out=EXP/f'codex_authored/T2/round_{r}/{pid}.json'
 if out.exists():continue
 c={'schema_version':'try4_repair_contract_v1','part_id':pid,'round':r,'status':d['status'],'failed_gates':ps['quality_gates']['failed'] or ['post_review_lod','post_review_visible_features'],'violations':[{'region':d['region'],'feature_id':feature['feature_id'],'type':d['type'],'severity':d['severity'],'requirement':feature['feature_type'],'evidence_views':['isolated_front','isolated_side','isolated_top','isolated_isometric'],'measured_difference':{'previous_metrics':{k:prev[k] for k in ('voxel_iou','normalized_chamfer','normalized_hd95')},'diagnosis':d['diagnosis']}}],'repair_actions':[{'priority':1,'action':'FULL_PART_REPLAN' if d['status']=='REPLAN' else 'MODIFY_PARAMETER','feature_id':feature['feature_id'],'target_region':d['region'],'cad_strategy':'structured round '+str(r)+' '+d['status'].lower(),'parameters':{'parameter_updates':d['updates']}}],'protected_features':d['protected'],'do_not_change':['semantic_role','interface_semantics','declared_open_spaces'],'review_inputs':{'gt_renders':f'artifacts/{pid[:3]}/isolated/{pid}','generated_renders':str((source/'renders').relative_to(EXP)),'semantic_label':json.loads((source/'agent_output.json').read_text())['mechanical_interpretation']['semantic_label_consumed'],'lod':'skills/robot_part_modeling_standard/SKILL.md','feature_graph':str((source/'feature_graph.json').relative_to(EXP)),'feature_tree':str((source/'feature_tree.json').relative_to(EXP)),'deterministic_metrics':ps['accepted_metrics'],'regional_discrepancies':f'results/phase6_regional_discrepancies.csv#{pid}','previous_history':ps['repair_history']}}
 jsonschema.validate(c,schema);out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(c,indent=2)+'\n')
print(len(dec['decisions']))
