"""Materialize current-agent review decisions into schema-valid contracts."""
import json
from pathlib import Path
import jsonschema,pandas as pd
ROOT=Path(__file__).resolve().parents[2];EXP=ROOT/'try4';dec=json.loads((EXP/'codex_authored/T2/round1_decisions.json').read_text());metrics=pd.read_csv(EXP/'results/phase5_metrics.csv');disc=pd.read_csv(EXP/'results/phase6_regional_discrepancies.csv').set_index('part_id');schema=json.loads((EXP/'schemas/repair_contract.schema.json').read_text())
for d in dec['decisions']:
    pid=d['part_id'];m=metrics[(metrics.part_id==pid)&(metrics.condition=='T1')].iloc[0];feature=json.loads((EXP/f'T1/{pid}/round_0/feature_graph.json').read_text())['features'][0];row=disc.loc[pid]
    measured={'voxel_iou':m.voxel_iou,'normalized_chamfer':m.normalized_chamfer,'normalized_hd95':m.normalized_hd95,'bbox_delta_generated_minus_gt_mm':[row.delta_generated_minus_gt_x_mm,row.delta_generated_minus_gt_y_mm,row.delta_generated_minus_gt_z_mm],'diagnosis':d['diagnosis']}
    c={'schema_version':'try4_repair_contract_v1','part_id':pid,'round':1,'status':d['status'],'failed_gates':m.failed_criteria.split(';'),'violations':[{'region':d['region'],'feature_id':feature['feature_id'],'type':d['type'],'severity':d['severity'],'requirement':feature['feature_type'],'evidence_views':['isolated_front','isolated_side','isolated_top','isolated_isometric'],'measured_difference':measured}],'repair_actions':[{'priority':1,'action':'FULL_PART_REPLAN' if d['status']=='REPLAN' else 'MODIFY_PARAMETER','feature_id':feature['feature_id'],'target_region':d['region'],'cad_strategy':'structured parameterized '+d['status'].lower(),'parameters':{'parameter_updates':d['updates']}}],'protected_features':d['protected'],'do_not_change':['semantic_role','interface_semantics','declared_open_spaces'],'review_inputs':{'gt_renders':f'artifacts/{pid[:3]}/isolated/{pid}','generated_renders':f'T1/{pid}/round_0/renders','semantic_label':json.loads((EXP/f'T1/{pid}/round_0/agent_output.json').read_text())['mechanical_interpretation']['semantic_label_consumed'],'lod':'skills/robot_part_modeling_standard/SKILL.md','feature_graph':f'T1/{pid}/round_0/feature_graph.json','feature_tree':f'T1/{pid}/round_0/feature_tree.json','deterministic_metrics':f'results/phase5_metrics.csv#{pid},T1','regional_discrepancies':f'results/phase6_regional_discrepancies.csv#{pid}','previous_history':[]}}
    jsonschema.validate(c,schema);out=EXP/f'codex_authored/T2/round_1/{pid}.json';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(c,indent=2)+'\n',encoding='utf-8')
print(len(dec['decisions']))
